version = 0.1

[default.deploy.parameters]
stack_name = "earned-screen-waitlist-api"
resolve_s3 = true
s3_prefix = "earned-screen-waitlist-api"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "eu-north-1"
